#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

pandoc hw1.md -s -o hw1.tex

pdflatex hw1.tex
bibtex hw1.aux
pdflatex hw1.tex
pdflatex hw1.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f hw1.tex

